### PR TITLE
honor do not track

### LINKED ISSUE #4: support do not track?
For the new dat site, I would like to honoring the user's do not track policy.

Seems like this be the right place to add, but not sure. It'd be as simple as:

```js
if (window.navigator.doNotTrack) return false
return window.navigator.sendBeacon(url, blob)
```

### PR DESCRIPTION
**Pull request by joehand**
Fixes #4 by checking do not track before sending beacon.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@joehand added you as a collaborator! :sparkles:

**Review by yoshuawuyts — APPROVED** [review]
:grin: excellent!

**Comment by yoshuawuyts** [comment]
Not sure if patch or major? - Kinda like the idea of respecting privacy to just be a patch release (:

**Comment by joehand** [comment]
agreed! Released as 1.0.3.

**Pull request merged**
